/-
  CEQ.V15
  -------
  Provenance: `CEQ_V15_CONTRACT.md` PART I §S-M (the Markov carrier) and PART II
  (THE LEAN INVENTORY). This file is the train-gate: items #1, #2, #5, #6, #7 plus
  #3, which the signed variant rides along on.

  | # | name                          | what is proved here |
  |---|-------------------------------|---------------------|
  | 1 | `chain_path_product`          | unrolling `y_s = a_s·y_{s-1} + b_s` gives, for each source `s`, the coefficient `∏_{k=s+1}^{n} a_k` — a PRODUCT along the path, not a sum of weights |
  | 2 | `prefix_logit_mask`           | `exp(C i − C j) = ∏_{k=j+1}^{i} a_k` for `C = scan(log a)`, `a > 0` |
  | 3 | `parity_sign`                 | `χ(P i − P j) = ∏_{k=j+1}^{i} χ(p k)` in `ZMod 2`, `χ` the sign character |
  | 5 | `gate_zero_is_attention`      | `g ≡ 0` ⇒ the masked hop is the causal all-ones mask |
  | 6 | `bounded_gates_stable`        | `g = −softplus w` ⇒ `a ∈ (0,1]`, path products `≤ 1` and antitone in path length |
  | 7 | `scan_assoc`                  | associativity of the AFFINE scan element `(a,b) ↦ (x ↦ a·x + b)` |

  Two of these are stated at a strength the contract's prose does not have, and the
  difference is the point of the file.

  **#5.** The contract says "`g == 0` gives the causal all-ones mask = standard
  attention" and calls this parity by identity bind. Both halves are proved below,
  but they are not the same statement. `gate_zero_is_attention` proves the first
  half exactly. `gate_zero_row_sum` then proves that this operator's row `i` sums to
  `i + 1`, not to `1`, and `gate_zero_not_stochastic` turns that into a refutation:
  §S-M's hop is explicitly UNNORMALIZED, so at `g ≡ 0` it is standard attention's
  MASK and is not any softmax row of any attention head. The identity bind
  that actually delivers parity is `gate_zero_logit_identity` — the gate entering the
  logits ADDITIVELY as `C i − C j`, where `g ≡ 0` leaves the logits and therefore
  every downstream row-normalization bit-identical. The multiplicative-unnormalized
  reading of §S-M does not give parity; the additive-logit reading does. Filed as a
  contract defect rather than proved around.

  **#7.** For the prefix sum of §S-M taken literally the monoid is `(ℝ, +)` and
  `scan_assoc` would be `add_assoc` — true, and vacuous as a licence for anything.
  The scan that a gated linear recurrence actually parallelizes composes AFFINE maps
  `x ↦ a·x + b`, and it is that monoid's associativity that licenses the log-depth
  route. `affApply_affComp` is included so the associativity is not associativity of
  an arbitrary binary operation: `affComp` is proved to be composition of the maps,
  and `chain_step_eq_affApply` proves those maps are the recurrence's own steps.

  No `sorry`.
-/

import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Algebra.BigOperators.Intervals
import Mathlib.Algebra.BigOperators.Order
import Mathlib.Algebra.Order.Ring.Lemmas
import Mathlib.Data.ZMod.Basic

namespace CEQ.V15

open BigOperators Finset

/-! ## The chain, and #1 -/

/-- The gated linear recurrence the Markov corpus labels are generated by:
    `y_0 = y₀`, `y_{s+1} = a_{s+1} · y_s + b_{s+1}`. -/
def chain (a b : ℕ → ℝ) (y₀ : ℝ) : ℕ → ℝ
  | 0 => y₀
  | s + 1 => a (s + 1) * chain a b y₀ s + b (s + 1)

/-- **#1 `chain_path_product`.**

    Unrolling the recurrence from `m` up to `n` gives a homogeneous term carrying
    `y_m` with coefficient `∏_{k=m+1}^{n} a_k`, and one term per source `s` with
    coefficient `∏_{k=s+1}^{n} a_k`.

    Every coefficient is a PRODUCT of consecutive gates along the path from the
    source to the target. Nothing here is a sum of per-position weights: the sum
    ranges over sources, and the composition along each path is multiplicative.
    This is the algebraic fact the contract's "WHERE WE ARE" section names as the
    campaign's one survivor, and `hop_eq_chain_coefficient` below matches it entry
    for entry against the prefix-logit operator of #2. -/
theorem chain_path_product (a b : ℕ → ℝ) (y₀ : ℝ) (m n : ℕ) (h : m ≤ n) :
    chain a b y₀ n =
      (∏ k in Ico (m + 1) (n + 1), a k) * chain a b y₀ m
        + ∑ s in Ico (m + 1) (n + 1), (∏ k in Ico (s + 1) (n + 1), a k) * b s := by
  induction n, h using Nat.le_induction with
  | base => simp
  | succ n hn ih =>
    have hmn : m + 1 ≤ n + 1 := Nat.succ_le_succ hn
    have hstep : chain a b y₀ (n + 1) = a (n + 1) * chain a b y₀ n + b (n + 1) := rfl
    have hsum : ∑ s in Ico (m + 1) (n + 1), (∏ k in Ico (s + 1) (n + 1 + 1), a k) * b s
        = a (n + 1) * ∑ s in Ico (m + 1) (n + 1), (∏ k in Ico (s + 1) (n + 1), a k) * b s := by
      rw [Finset.mul_sum]
      refine Finset.sum_congr rfl (fun s hs => ?_)
      have hs' : s + 1 ≤ n + 1 :=
        Nat.succ_le_succ (Nat.lt_succ_iff.mp (Finset.mem_Ico.mp hs).2)
      rw [Finset.prod_Ico_succ_top hs']
      ring
    rw [hstep, ih, Finset.prod_Ico_succ_top hmn, Finset.sum_Ico_succ_top hmn]
    simp only [Finset.Ico_self, Finset.prod_empty, one_mul]
    rw [hsum]
    ring

/-- The single-impulse corollary, which is #1 in the shape the contract writes it:
    a lone drive at position `m+1` reaching the state at `n` is multiplied by the
    product of exactly the gates strictly between them. -/
theorem chain_impulse_path_product (a b : ℕ → ℝ) (y₀ : ℝ) (m n : ℕ) (h : m < n)
    (hy : chain a b y₀ m = 0) (hb : ∀ s, m + 1 < s → s ≤ n → b s = 0) :
    chain a b y₀ n = (∏ k in Ico (m + 2) (n + 1), a k) * b (m + 1) := by
  rw [chain_path_product a b y₀ m n h.le, hy, mul_zero, zero_add]
  rw [Finset.sum_eq_single (m + 1)]
  · intro s hs hne
    have h1 : m + 1 < s := lt_of_le_of_ne (Finset.mem_Ico.mp hs).1 (Ne.symm hne)
    have h2 : s ≤ n := Nat.lt_succ_iff.mp (Finset.mem_Ico.mp hs).2
    rw [hb s h1 h2, mul_zero]
  · intro hmem
    exact absurd (Finset.mem_Ico.mpr ⟨le_refl _, Nat.succ_lt_succ h⟩) hmem

/-! ## The prefix-logit carrier, and #2 -/

/-- `C = scan(g)`, the inclusive prefix sum of the log-gates. -/
def scan (g : ℕ → ℝ) (i : ℕ) : ℝ := ∑ k in range (i + 1), g k

/-- The unnormalized causal hop of §S-M, `W_ij = exp(C_i − C_j)`. -/
noncomputable def W (g : ℕ → ℝ) (i j : ℕ) : ℝ := Real.exp (scan g i - scan g j)

/-- **#2 `prefix_logit_mask`.**

    With `g k = log (a k)` and `a k > 0`, the prefix-logit hop is exactly the path
    product of the gates strictly after the source and up to the target.

    The positivity hypothesis is load-bearing and is stated, not assumed away: for
    `a k ≤ 0` the left side is still a positive number while the right side need not
    be, so the identity is false without it. `parity_sign` (#3) is what carries the
    sign that positivity gives up. -/
theorem prefix_logit_mask (a : ℕ → ℝ) (ha : ∀ k, 0 < a k) {i j : ℕ} (hij : j ≤ i) :
    W (fun k => Real.log (a k)) i j = ∏ k in Ico (j + 1) (i + 1), a k := by
  have h : ∑ k in Ico (j + 1) (i + 1), Real.log (a k)
      = scan (fun k => Real.log (a k)) i - scan (fun k => Real.log (a k)) j := by
    simpa [scan] using Finset.sum_Ico_eq_sub (fun k => Real.log (a k)) (Nat.succ_le_succ hij)
  rw [W, ← h, Real.exp_sum]
  exact Finset.prod_congr rfl (fun k _ => Real.exp_log (ha k))

/-- **#1 bound to #2.** The prefix-logit operator does not merely resemble the
    chain's path coefficients — applied to the drive `b` it reproduces the chain
    exactly. This is the identity the ARM PL's oracle-gate bind is supposed to hit
    numerically; here it is at exact arithmetic. -/
theorem prefix_logit_computes_chain (a b : ℕ → ℝ) (ha : ∀ k, 0 < a k) (i : ℕ) :
    chain a b 0 i = ∑ s in Ico 1 (i + 1), W (fun k => Real.log (a k)) i s * b s := by
  have h := chain_path_product a b 0 0 i (Nat.zero_le i)
  have hc : chain a b 0 0 = 0 := rfl
  rw [h, hc, mul_zero, zero_add]
  norm_num
  refine Finset.sum_congr rfl (fun s hs => ?_)
  rw [prefix_logit_mask a ha (Nat.lt_succ_iff.mp (Finset.mem_Ico.mp hs).2)]

/-! ## The signed variant, and #3 -/

/-- The sign character of `ZMod 2`: `χ 0 = 1`, `χ 1 = −1`. This is `(−1)^·`. -/
def chi (x : ZMod 2) : ℝ := if x = 0 then 1 else -1

lemma zmod_two_cases : ∀ x : ZMod 2, x = 0 ∨ x = 1 := by decide

@[simp] lemma chi_zero : chi 0 = 1 := by simp [chi]

@[simp] lemma chi_one : chi 1 = -1 := by
  have h : (1 : ZMod 2) ≠ 0 := by decide
  simp [chi, h]

/-- `χ` is multiplicative on XOR: in `ZMod 2`, `+` IS exclusive-or. -/
lemma chi_add (x y : ZMod 2) : chi (x + y) = chi x * chi y := by
  have h11 : (1 : ZMod 2) + 1 = 0 := by decide
  rcases zmod_two_cases x with rfl | rfl <;> rcases zmod_two_cases y with rfl | rfl <;>
    simp only [zero_add, add_zero, h11, chi_zero, chi_one] <;> norm_num

lemma chi_sum (p : ℕ → ZMod 2) (s : Finset ℕ) :
    chi (∑ k in s, p k) = ∏ k in s, chi (p k) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert h ih => rw [Finset.sum_insert h, Finset.prod_insert h, chi_add, ih]

/-- `P = prefix-XOR of the sign bits`, written as a prefix sum in `ZMod 2`. -/
def pscan (p : ℕ → ZMod 2) (i : ℕ) : ZMod 2 := ∑ k in range (i + 1), p k

/-- In `ZMod 2` the prefix-sum difference that #2 takes IS the prefix XOR that §S-M's
    parity mask takes. Recorded so `parity_sign` can be read either way. -/
lemma pscan_sub_eq_add (p : ℕ → ZMod 2) (i j : ℕ) :
    pscan p i - pscan p j = pscan p i + pscan p j :=
  CharTwo.sub_eq_add _ _

/-- **#3 `parity_sign`.**

    `(−1)^(P i XOR P j)` is the product of the signs along the path from `j` to `i` —
    the same path, the same endpoints, and the same multiplicative composition as
    #2's magnitude. The signed carrier is therefore the pair (`W`, `χ`), not a
    separate mechanism. -/
theorem parity_sign (p : ℕ → ZMod 2) {i j : ℕ} (hij : j ≤ i) :
    chi (pscan p i - pscan p j) = ∏ k in Ico (j + 1) (i + 1), chi (p k) := by
  have h : ∑ k in Ico (j + 1) (i + 1), p k = pscan p i - pscan p j := by
    simpa [pscan] using Finset.sum_Ico_eq_sub p (Nat.succ_le_succ hij)
  rw [← h, chi_sum]

/-! ## #5 — the zero gate -/

/-- The hop as it is actually applied: causally masked, `0` above the diagonal. -/
noncomputable def Wc (g : ℕ → ℝ) (i j : ℕ) : ℝ := if j ≤ i then W g i j else 0

/-- **#5 `gate_zero_is_attention`.**

    `g ≡ 0` makes the masked hop the indicator of `j ≤ i` — the causal all-ones
    mask, which is exactly standard attention's mask. Stated for ALL `i, j`, so the
    above-diagonal half is included rather than quietly dropped: note that the
    causality is supplied by `Wc`'s mask, NOT derived from the gate, since
    `W g i j = 1` above the diagonal too when `g ≡ 0`. -/
theorem gate_zero_is_attention (g : ℕ → ℝ) (hg : ∀ k, g k = 0) (i j : ℕ) :
    Wc g i j = if j ≤ i then 1 else 0 := by
  have hs : ∀ n, scan g n = 0 := fun n => by simp [scan, hg]
  simp [Wc, W, hs]

/-- **The contract defect, proved.**

    §S-M's hop is UNNORMALIZED. At `g ≡ 0` its row `i` sums to `i + 1`, so it is not
    a row-stochastic attention matrix for any `i ≥ 1`; it is standard attention's
    MASK. "`g == 0` gives bitwise standard attention" is therefore false for the
    multiplicative-unnormalized reading of §S-M — the operator differs from a
    softmax row by the factor `i + 1` — and the parity bind has to be taken in the
    additive-logit reading below. -/
theorem gate_zero_row_sum (g : ℕ → ℝ) (hg : ∀ k, g k = 0) (i : ℕ) :
    ∑ j in range (i + 1), Wc g i j = (i : ℝ) + 1 := by
  have h : ∀ j ∈ range (i + 1), Wc g i j = 1 := by
    intro j hj
    rw [gate_zero_is_attention g hg i j,
      if_pos (Nat.lt_succ_iff.mp (Finset.mem_range.mp hj))]
  rw [Finset.sum_congr rfl h, Finset.sum_const, Finset.card_range, nsmul_eq_mul, mul_one]
  push_cast
  ring

/-- **The refutation, in one line.** Every row of a softmax attention matrix sums to
    `1`. For `i ≥ 1` the `g ≡ 0` row of §S-M's unnormalized hop sums to `i + 1 ≠ 1`,
    so it is not any softmax row of any attention head with any weights. The
    contract's PARITY clause — "`g == 0` gives bitwise standard attention" — is
    therefore FALSE as stated for §S-M's operator. Smallest witness: `i = 1`, row sum
    `2`. -/
theorem gate_zero_not_stochastic (g : ℕ → ℝ) (hg : ∀ k, g k = 0) {i : ℕ} (hi : 1 ≤ i) :
    ∑ j in range (i + 1), Wc g i j ≠ 1 := by
  rw [gate_zero_row_sum g hg]
  have h : (1 : ℝ) ≤ (i : ℝ) := by exact_mod_cast hi
  intro hc
  linarith

/-- **`softmax_unique_absorbing`, wall (b) — the ZERO WALL.**

    Two facts about the raw exponential score, for ANY gate `g`, no hypothesis
    needed on `g` at all:

    * row `0` is absorbing purely from the causal mask — the only column
      row `0` can see is `j = 0` itself, so `Wc g 0 j` is the indicator of
      `j = 0`, exactly `Asink`'s BOS-sink slot and exactly the
      `P[0, 0] == 1 always` refusal `ceqjepa/operator.py`'s module docstring
      states for any causal mask;
    * every OTHER row `i ≥ 1` leaks a strictly positive amount back to column
      `0`: `Wc g i 0 = W g i 0 = exp(scan g i − scan g 0)`, and `exp` is
      strictly positive for every finite real (`Real.exp_pos`).

    Read together: on a causal chain built from `exp`, index `0` is the only
    row that can be a closed absorbing class. No other single row `i ≥ 1` can
    be closed on its own, because it always sends positive mass to `0`. That
    is the uniqueness `gate_zero_second_absorbing` below shows the raw score
    cannot escape by itself — only an explicit gate can. -/
theorem softmax_unique_absorbing (g : ℕ → ℝ) :
    (∀ j, Wc g 0 j = if j = 0 then 1 else 0) ∧ ∀ i, 1 ≤ i → 0 < Wc g i 0 := by
  refine ⟨fun j => ?_, fun i _ => ?_⟩
  · by_cases hj : j = 0
    · subst hj
      simp [Wc, W]
    · have hjpos : ¬ j ≤ 0 := fun h => hj (Nat.le_zero.mp h)
      simp [Wc, hjpos, hj]
  · have h0i : (0 : ℕ) ≤ i := Nat.zero_le i
    simp only [Wc, if_pos h0i]
    exact Real.exp_pos _

/-- A boundary-overwrite gate on top of the causal hop: `m i j` multiplies the
    `(i, j)` entry of `Wc`, independently of the score `g`. This is the Lean
    shape of `ceqjepa/operator.py`'s `build_operator` boundary overwrite —
    "declared absorbing rows are overwritten to identity ROWS ... AFTER the
    softmax" — factored as a multiplicative mask so the causal zeros of `Wc`
    (every `j > i`) survive untouched no matter what `m` says there. -/
noncomputable def Wgate (g : ℕ → ℝ) (m : ℕ → ℕ → ℝ) (i j : ℕ) : ℝ := m i j * Wc g i j

/-- **`gate_zero_second_absorbing`.**

    `softmax_unique_absorbing` shows the raw score alone can never make row
    `1` absorbing: `Wc g 1 0 > 0` for every `g`, by the ZERO WALL. An
    explicit gate `m`, independent of `g`, can. Zeroing exactly the one edge
    `m 1 0 = 0` and leaving the diagonal `m 1 1 = 1` untouched collapses row
    `1` to `e_1` — the identity row — for EVERY score `g`: the causal mask
    already zeroes every `j > 1` inside `Wc` regardless of `m`, so the two
    edges `m` actually reaches (`j = 0` and `j = 1`) are the entire row. Row
    `1` becomes a SECOND closed absorbing class, bought entirely by the gate.
    This is exactly what strict positivity of `exp` forbids the plain
    softmax score from doing on its own. -/
theorem gate_zero_second_absorbing (g : ℕ → ℝ) (m : ℕ → ℕ → ℝ)
    (h0 : m 1 0 = 0) (h1 : m 1 1 = 1) (j : ℕ) :
    Wgate g m 1 j = if j = 1 then 1 else 0 := by
  by_cases hj1 : j = 1
  · subst hj1
    simp [Wgate, Wc, h1, W]
  · have hcase : ¬ j ≤ 1 ∨ j = 0 := by omega
    rcases hcase with hgt | hz
    · simp [Wgate, Wc, hgt, hj1]
    · subst hz
      simp [Wgate, Wc, h0, hj1]

/-- **#5, the reading that actually delivers parity.**

    Take the gate into the logits ADDITIVELY, on top of whatever logits `q` the
    attention head already computes. At `g ≡ 0` the logit is `q i j` unchanged, so
    the softmax row — and every quantity downstream of it — is bit-identical to
    standard attention. This, not `gate_zero_is_attention`, is the identity bind the
    contract's PARITY clause needs. -/
theorem gate_zero_logit_identity (g : ℕ → ℝ) (hg : ∀ k, g k = 0) (q : ℕ → ℕ → ℝ)
    (i j : ℕ) : q i j + (scan g i - scan g j) = q i j := by
  have hs : ∀ n, scan g n = 0 := fun n => by simp [scan, hg]
  simp [hs]

/-! ## #6 — bounded gates -/

/-- `softplus w = log (1 + exp w)`. -/
noncomputable def softplus (w : ℝ) : ℝ := Real.log (1 + Real.exp w)

lemma softplus_pos (w : ℝ) : 0 < softplus w :=
  Real.log_pos (by linarith [Real.exp_pos w])

/-- **#6 `bounded_gates_stable`, part 1.** `g = −softplus w` ⇒ `a = exp g ∈ (0, 1]`.
    The upper bound is in fact strict, which is stronger than the contract asks. -/
theorem bounded_gates_stable (w : ℝ) :
    0 < Real.exp (-softplus w) ∧ Real.exp (-softplus w) ≤ 1 :=
  ⟨Real.exp_pos _, le_of_lt (Real.exp_lt_one_iff.mpr (by linarith [softplus_pos w]))⟩

/-- **#6, part 2.** Every path product of `−softplus`-parametrized gates is `≤ 1`. -/
theorem bounded_gates_prod_le_one (w : ℕ → ℝ) (s : Finset ℕ) :
    ∏ k in s, Real.exp (-softplus (w k)) ≤ 1 :=
  Finset.prod_le_one (fun k _ => (bounded_gates_stable (w k)).1.le)
    (fun k _ => (bounded_gates_stable (w k)).2)

/-- **#6, part 3 — the stationarity claim.** Path products are non-increasing in path
    length: extending the path backwards from `j` to `j' ≤ j` can only shrink it. No
    lengthening of a path can amplify. -/
theorem bounded_gates_antitone (w : ℕ → ℝ) {j' j i : ℕ} (h1 : j' ≤ j) (h2 : j ≤ i) :
    ∏ k in Ico j' i, Real.exp (-softplus (w k))
      ≤ ∏ k in Ico j i, Real.exp (-softplus (w k)) := by
  rw [← Finset.prod_Ico_consecutive _ h1 h2]
  exact mul_le_of_le_one_left
    (Finset.prod_nonneg (fun k _ => (Real.exp_pos _).le))
    (bounded_gates_prod_le_one w _)

/-! ## #7 — the scan monoid -/

/-- One scan element: the pair `(a, b)` standing for the affine map `x ↦ a·x + b`.
    This — not `(ℝ, +)` — is the monoid a gated linear recurrence scans over. -/
abbrev Aff := ℝ × ℝ

/-- The map an element denotes. -/
def affApply (p : Aff) (x : ℝ) : ℝ := p.1 * x + p.2

/-- Composition in application order: `affComp p q` applies `p`, then `q`. -/
def affComp (p q : Aff) : Aff := (q.1 * p.1, q.1 * p.2 + q.2)

/-- `affComp` really is composition of the denoted maps. Without this,
    `scan_assoc` would be associativity of an arbitrary binary operation and would
    licence nothing. -/
theorem affApply_affComp (p q : Aff) (x : ℝ) :
    affApply (affComp p q) x = affApply q (affApply p x) := by
  simp only [affApply, affComp]
  ring

/-- The elements being scanned are the recurrence's own steps. -/
theorem chain_step_eq_affApply (a b : ℕ → ℝ) (y₀ : ℝ) (s : ℕ) :
    chain a b y₀ (s + 1) = affApply (a (s + 1), b (s + 1)) (chain a b y₀ s) := rfl

/-- **#7 `scan_assoc`.** The scan operator is associative, so the sequential
    left-to-right fold and any balanced-tree reassociation compute the same element.
    This is what licenses the log-depth parallel route. -/
theorem scan_assoc (p q r : Aff) : affComp (affComp p q) r = affComp p (affComp q r) := by
  simp only [affComp, Prod.mk.injEq]
  constructor <;> ring

theorem affComp_id (p : Aff) : affComp p (1, 0) = p := by simp [affComp]

theorem id_affComp (p : Aff) : affComp (1, 0) p = p := by simp [affComp]

/-- The gate-only submonoid: with `b = 0` the scan multiplies gates, and `scan` of
    #2 is that product read through `log`. The `(ℝ, +)` prefix sum of §S-M is this
    image, which is why `add_assoc` alone was never the content of #7. -/
theorem affComp_gate_only (a a' : ℝ) : affComp (a, 0) (a', 0) = (a' * a, 0) := by
  simp [affComp]

end CEQ.V15
