"""Found-data curl response to do(delete edge): Binance spot pair removals, 2026-08-14.

THE INTERVENTION. Binance removed seven spot trading pairs at 2026-08-14 03:00 UTC:
APT/BTC, AR/BTC, A/USDC, BTTC/TRY, CYBER/USDC, LPT/BTC, WAL/FDUSD. The announcement
states the base and quote assets remain tradable on other pairs. That is do(delete
edge) with the NODES LEFT STANDING and every other edge still quoted -- the shape
every synthetic bed in this repo has had to manufacture.

VERIFIED IN THE DATA, not taken on the announcement's word: each removed pair has a
full 1440-row 1m file on 2026-08-13, a 180-row file on 2026-08-14 (00:00-02:59 UTC),
and no file on 2026-08-15. The cut is where the announcement says it is.

THE OBJECT. On spot pairs, log price is an edge cochain: for a pair with base b and
quote q, w(b->q) = log(close) is "one b buys e^w q", antisymmetric by construction.
A triangle (i,j,k) carries c_T = w(i->j) + w(j->k) + w(k->i), which is exactly the
triangular-arbitrage residual. Zero curl == prices are generated by a single
numeraire potential. Orientation is dr1.Complex's: d1 row = +e(a,b) +e(b,c) -e(a,c)
on sorted (a,b,c), which is that sum. The complex is built with dr1.Complex and its
d1 @ d0 == 0 is asserted before anything is measured; market_curl.pairing_complex is
the same construction but enumerates triples in O(n^3) over nodes, which is fine for
6 teams and not for 500 assets, so the triangles are enumerated off the adjacency
here and handed to the same Complex.

THE HYPOTHESIS. Removing an edge removes an arbitrage PATH, so curl on triangles
that still stand but shared a node with a removed edge should RISE after 03:00 UTC
relative to triangles that did not. The LEVELS question is already answered in the
literature (curl sits at the spread floor); the RESPONSE question is what is open.

THE GATE, AND IT RUNS FIRST. Klines are NOT synchronous. A 1m bar's close is a
last-trade price, not a simultaneous snapshot across three books, so a thin leg's
stale price manufactures curl that is pure microstructure. THE TEST: regress
pre-intervention per-triangle mean |c_T| on (a) the summed half-spread proxy of the
three legs and (b) the summed inverse volume of the three legs. If |c_T| tracks
1/volume rather than spread, the measurement is reading staleness and is VOID.
gate() returns that verdict and main() stops on it.

--selfcheck runs offline on synthetic data and carries a PLANTED NEGATIVE: a
staleness-only regime whose curl is manufactured entirely by asynchronous quoting.
The gate must VOID it. If it does not, the gate is decorative and every number
downstream is unearned.

RUN:  python -m ceqjepa.binance_curl --selfcheck     (offline, no network)
      python -m ceqjepa.binance_curl                  (downloads to the scratchpad)
"""

import argparse
import csv
import io
import itertools
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
import zipfile
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta, timezone

import numpy as np

from ceqjepa.dr1 import Complex

__all__ = ["build_complex", "triangle_panels", "gate", "did", "REMOVED_PAIRS"]

# ---------------------------------------------------------------------------
# The intervention, as published.
REMOVED_PAIRS = [("APT", "BTC"), ("AR", "BTC"), ("A", "USDC"), ("BTTC", "TRY"),
                 ("CYBER", "USDC"), ("LPT", "BTC"), ("WAL", "FDUSD")]
CUT = datetime(2026, 8, 14, 3, 0, tzinfo=timezone.utc)
PLACEBO_CUT = CUT - timedelta(days=1)
WINDOW = timedelta(hours=6)

# Quotes, longest first: symbol parsing strips the longest matching suffix, so
# BTCFDUSD reads as BTC/FDUSD and not as BTCFD/USD.
QUOTES = ("FDUSD", "USDT", "USDC", "TRY", "BTC", "BNB", "ETH")

GRID_START = PLACEBO_CUT - WINDOW                 # 2026-08-12 21:00 UTC
GRID_END = CUT + WINDOW                           # 2026-08-14 09:00 UTC
DAYS = ["2026-08-12", "2026-08-13", "2026-08-14"]

MIN_MINUTES = 60      # a triangle needs this many quoted minutes in EVERY window
BUCKET = "https://data.binance.vision/data/spot/daily/klines/%s/1m/%s-1m-%s.zip"
LIST_URL = ("https://s3-ap-northeast-1.amazonaws.com/data.binance.vision"
            "?delimiter=/&prefix=data/spot/daily/klines/&max-keys=1000")


def _cache():
    d = os.environ.get("CEQ_BINANCE_CACHE") or os.path.join(
        os.environ.get("TEMP", "/tmp"), "claude", "binance_curl_cache")
    os.makedirs(d, exist_ok=True)
    return d


# ---------------------------------------------------------------------------
# Data. Nothing here is called by --selfcheck.

def list_symbols():
    """Every spot symbol in the public bucket. Listed, never guessed -- AUSDC is
    A/USDC and ARBTC is AR/BTC, and no naming convention tells you that."""
    path = os.path.join(_cache(), "symbols.json")
    if os.path.exists(path):
        return json.load(open(path))
    syms, marker = [], ""
    while True:
        url = LIST_URL + ("&marker=" + urllib.parse.quote(marker) if marker else "")
        body = urllib.request.urlopen(url, timeout=90).read().decode()
        page = [p.split("</Prefix>")[0].rstrip("/").rsplit("/", 1)[-1]
                for p in body.split("<Prefix>")[1:] if "</Prefix>" in p]
        page = [s for s in page if s and s != "klines"]
        syms.extend(page)
        if "<IsTruncated>true</IsTruncated>" not in body:
            break
        marker = body.split("<NextMarker>")[1].split("</NextMarker>")[0]
    syms = sorted(set(syms))
    json.dump(syms, open(path, "w"))
    return syms


def split_symbol(sym):
    for q in QUOTES:
        if sym.endswith(q) and len(sym) > len(q):
            return sym[:-len(q)], q
    return None


def fetch_day(sym, day):
    """(minute_index, close, high, low, n_trades) for one symbol-day, or None.
    A 404 is cached as a marker file: a pair that did not trade that day is a
    fact about the intervention, not a transient failure to retry."""
    raw = os.path.join(_cache(), "%s-%s.zip" % (sym, day))
    miss = raw + ".missing"
    if os.path.exists(miss):
        return None
    if not os.path.exists(raw):
        try:
            b = urllib.request.urlopen(BUCKET % (sym, sym, day), timeout=90).read()
        except urllib.error.HTTPError as e:
            if e.code == 404:
                open(miss, "w").close()
                return None
            raise
        open(raw, "wb").write(b)
    with zipfile.ZipFile(raw) as z:
        txt = z.read(z.namelist()[0]).decode()
    rows = list(csv.reader(io.StringIO(txt)))
    if not rows:
        return None
    if not rows[0][0].lstrip("-").replace(".", "", 1).isdigit():
        rows = rows[1:]                                    # newer files carry a header
    a = np.array(rows, dtype=np.float64)
    t = a[:, 0]
    t = t / 1e6 if t.max() > 1e15 else (t / 1e3 if t.max() > 1e12 else t)
    minute = np.rint((t - GRID_START.timestamp()) / 60.0).astype(np.int64)
    return minute, a[:, 4], a[:, 2], a[:, 3], a[:, 8]      # close, high, low, n_trades


def load_panel(symbols):
    """Dense minute grid per symbol: log close, half-spread proxy, inverse volume.
    NaN where the pair published no bar at all."""
    n_min = int((GRID_END - GRID_START).total_seconds() // 60)
    out = {}
    jobs = [(s, d) for s in symbols for d in DAYS]

    def one(j):
        try:
            return j[0], fetch_day(*j)
        except Exception as e:                 # a broken zip is a dropped symbol-day
            print("  warn %s %s: %s" % (ascii(j[0]), j[1], e), file=sys.stderr)
            return j[0], None

    with ThreadPoolExecutor(24) as ex:
        for sym, r in ex.map(one, jobs):
            if r is None:
                continue
            minute, close, high, low, ntr = r
            ok = (minute >= 0) & (minute < n_min) & (close > 0)
            if not ok.any():
                continue
            arr = out.setdefault(sym, np.full((3, n_min), np.nan))
            m = minute[ok]
            arr[0, m] = np.log(close[ok])
            arr[1, m] = (high[ok] - low[ok]) / (2.0 * close[ok])
            arr[2, m] = 1.0 / (1.0 + ntr[ok])
    return out, n_min


# ---------------------------------------------------------------------------
# The complex and the cochain.

def build_complex(edges):
    """edges: iterable of (u, v) asset-name pairs that are quoted. Triangles are
    triples all three of whose pairs are quoted; a triple missing one quote is not
    a triangle and is dropped, not imputed."""
    nodes = sorted({x for e in edges for x in e})
    ix = {a: i for i, a in enumerate(nodes)}
    adj = {}
    have = set()
    for u, v in edges:
        i, j = ix[u], ix[v]
        adj.setdefault(i, set()).add(j)
        adj.setdefault(j, set()).add(i)
        have.add((min(i, j), max(i, j)))
    tri = []
    for a in sorted(adj):
        nb = sorted(x for x in adj[a] if x > a)
        for b, c in itertools.combinations(nb, 2):
            if (b, c) in have:
                tri.append((a, b, c))
    cx = Complex(len(nodes), tri)
    assert float(np.abs(cx.d1 @ cx.d0).max()) < 1e-12, \
        "d1 @ d0 != 0: this is not a complex and every curl below is arithmetic error"
    return cx, nodes, ix


def triangle_panels(cx, edge_series):
    """(curl, spread, invvol, any_stale) as (n_triangles, n_minutes).

    any_stale marks triangle-minutes where at least one leg published a bar with
    ZERO trades in it -- a bar whose close is literally the previous close carried
    forward. It is the sharpest staleness flag the kline schema affords, and the
    gate is run a second time with those minutes dropped so that a VOID verdict
    cannot be blamed on not having tried the obvious repair.

    edge_series[e] = (log_price_series_oriented_low_to_high, half_spread, invvol)
    for cx.edges[e]. The curl is taken by index rather than by d1 @ omega because
    d1 is mostly zeros and 0 * nan = nan -- a matmul would poison every triangle
    the moment one pair went unquoted for one minute.
    """
    eix = {e: i for i, e in enumerate(cx.edges)}
    OM = np.stack([edge_series[i][0] for i in range(len(cx.edges))])
    HS = np.stack([edge_series[i][1] for i in range(len(cx.edges))])
    IV = np.stack([edge_series[i][2] for i in range(len(cx.edges))])
    ia = np.array([eix[(t[0], t[1])] for t in cx.triangles])
    ib = np.array([eix[(t[1], t[2])] for t in cx.triangles])
    ic = np.array([eix[(t[0], t[2])] for t in cx.triangles])
    stale = (IV[ia] >= 1.0) | (IV[ib] >= 1.0) | (IV[ic] >= 1.0)
    return (OM[ia] + OM[ib] - OM[ic], HS[ia] + HS[ib] + HS[ic],
            IV[ia] + IV[ib] + IV[ic], stale)


# ---------------------------------------------------------------------------
# Statistics. Two OLS columns and a Welch interval; nothing that needs a library.

def _ols(y, X):
    beta, *_ = np.linalg.lstsq(X, y, rcond=None)
    resid = y - X @ beta
    dof = max(len(y) - X.shape[1], 1)
    s2 = float(resid @ resid) / dof
    cov = s2 * np.linalg.pinv(X.T @ X)
    se = np.sqrt(np.clip(np.diag(cov), 0, None))
    r2 = 1.0 - float(resid @ resid) / max(float(((y - y.mean()) ** 2).sum()), 1e-300)
    return beta, np.divide(beta, se, out=np.zeros_like(beta), where=se > 0), r2


def _z(v):
    s = v.std(ddof=1)
    return (v - v.mean()) / s if s > 0 else np.zeros_like(v)


def gate(abs_curl, spread, invvol, t_bar=3.0):
    """THE GATE. Does pre-intervention |c_T| track spread, or 1/volume?

    All three inputs are per-triangle means over the pre-intervention window, so
    the observation is the triangle and no clustering correction is owed.

    VOID when the standardized 1/volume coefficient beats the spread coefficient
    in magnitude and clears |t| > t_bar. The rule is fixed before the numbers are
    seen; this project has already shipped a bar applied in two incompatible units
    and the fix is to state the rule in one unit, in advance.
    """
    n = len(abs_curl)
    if n < 30:
        return dict(verdict="REFUSED", reason="only %d triangles" % n, n=n)
    y, x1, x2 = _z(abs_curl), _z(spread), _z(invvol)
    X = np.column_stack([np.ones(n), x1, x2])
    beta, t, r2 = _ols(y, X)
    b_sp, b_iv, t_sp, t_iv = beta[1], beta[2], t[1], t[2]
    _, _, r2_sp = _ols(y, np.column_stack([np.ones(n), x1]))
    _, _, r2_iv = _ols(y, np.column_stack([np.ones(n), x2]))
    void = abs(b_iv) > abs(b_sp) and abs(t_iv) > t_bar
    return dict(verdict="VOID" if void else "PASS", n=n,
                beta_spread=float(b_sp), t_spread=float(t_sp),
                beta_invvol=float(b_iv), t_invvol=float(t_iv),
                r2_joint=float(r2), r2_spread_only=float(r2_sp),
                r2_invvol_only=float(r2_iv),
                rho_spread=float(_spearman(abs_curl, spread)),
                rho_invvol=float(_spearman(abs_curl, invvol)))


def _spearman(a, b):
    ra, rb = _rank(a), _rank(b)
    ra, rb = ra - ra.mean(), rb - rb.mean()
    d = np.sqrt((ra @ ra) * (rb @ rb))
    return float(ra @ rb / d) if d > 0 else 0.0


def _rank(v):
    o = np.argsort(v, kind="mergesort")
    r = np.empty(len(v), float)
    r[o] = np.arange(len(v), dtype=float)
    return r


def did(delta_treated, delta_control):
    """Difference-in-differences on per-triangle (post - pre) mean |c_T|, with a
    Welch 95% interval. Refuses rather than reporting a difference of means when
    either group is too small to have a spread -- a group of two is not a group."""
    a, b = np.asarray(delta_treated), np.asarray(delta_control)
    if len(a) < 3 or len(b) < 3:
        return dict(verdict="REFUSED", n_treated=len(a), n_control=len(b))
    va, vb = a.var(ddof=1) / len(a), b.var(ddof=1) / len(b)
    se = float(np.sqrt(va + vb))
    d = float(a.mean() - b.mean())
    return dict(did=d, se=se, lo=d - 1.96 * se, hi=d + 1.96 * se,
                t=d / se if se > 0 else float("nan"),
                mean_treated=float(a.mean()), mean_control=float(b.mean()),
                n_treated=len(a), n_control=len(b), verdict="OK")


def window_means(curl, spread, invvol, sl, drop=None):
    """Per-triangle window means and the count of usable minutes. drop, if given,
    is a boolean panel of minutes to exclude (used to drop zero-trade bars)."""
    c = np.abs(curl[:, sl]) * 1e4                     # basis points
    ok = np.isfinite(c)
    if drop is not None:
        ok &= ~drop[:, sl]
    n = ok.sum(1)
    with np.errstate(invalid="ignore"):
        mc = np.where(n > 0, np.nansum(np.where(ok, c, 0.0), 1) / np.maximum(n, 1), np.nan)
        ms = np.nanmean(np.where(np.isfinite(spread[:, sl]), spread[:, sl], np.nan), 1)
        mv = np.nanmean(np.where(np.isfinite(invvol[:, sl]), invvol[:, sl], np.nan), 1)
    return mc, ms, mv, n


# ---------------------------------------------------------------------------
# Self-check: offline, synthetic, with a planted negative.

def _synth(n_nodes=14, n_min=800, seed=0, regime="spread", treat=None, rise=0.0):
    """Synthetic edge series on a complete graph over n_nodes assets.

    'spread'    every leg trades every minute; the quoted price is the true
                numeraire price plus a bid-ask jitter whose size is the leg's
                spread. Volume varies but is drawn INDEPENDENTLY of spread.
                Curl here is a spread phenomenon: the gate must PASS.
    'stale'     THE PLANTED NEGATIVE. Every leg is on the true price exactly --
                no spread at all, spreads drawn independently -- but each leg's
                quote is a LAST TRADE from up to k minutes ago, k set by the
                leg's own activity. Curl here is manufactured entirely by
                asynchronous quoting: the gate must VOID it.
    """
    rng = np.random.default_rng(seed)
    r = np.cumsum(rng.normal(0, 3e-4, size=(n_nodes, n_min + 64)), axis=1)
    edges = [(i, j) for i in range(n_nodes) for j in range(i + 1, n_nodes)]
    cx, _, _ = build_complex([("N%02d" % i, "N%02d" % j) for i, j in edges])
    series = []
    for (i, j) in cx.edges:
        halfspread = 10 ** rng.uniform(-4.3, -3.0)
        ntr = 10 ** rng.uniform(0.0, 2.7)
        if regime == "spread":
            om = r[i, 64:] - r[j, 64:] + rng.normal(0, halfspread, n_min)
            lag = np.zeros(n_min, dtype=int)
        else:
            halfspread = 10 ** rng.uniform(-4.3, -3.0)          # independent of ntr
            lag = rng.poisson(60.0 / ntr, n_min).clip(0, 60)
            idx = np.arange(n_min) + 64 - lag
            om = r[i, idx] - r[j, idx]
        series.append([om,
                       np.full(n_min, halfspread) * (1.0 + 0.2 * rng.normal(size=n_min)),
                       np.full(n_min, 1.0 / (1.0 + ntr))])
    curl, spread, invvol, _ = triangle_panels(cx, series)
    if treat is not None and rise > 0:
        m = np.array([bool(set(t) & set(treat)) for t in cx.triangles])
        curl[m, n_min // 2:] += rng.normal(0, rise, (int(m.sum()), n_min - n_min // 2))
    return cx, curl, spread, invvol


def selfcheck():
    n_min = 800
    half = slice(0, n_min // 2), slice(n_min // 2, n_min)

    print("(a) THE COMPLEX. d1 @ d0 == 0 is asserted inside build_complex(); a")
    print("    complex that fails it makes every curl below an arithmetic error.")
    cx, curl, spread, invvol = _synth(regime="spread")
    print("    %s" % cx)

    print("(b) THE NULL IS EXACT. Prices from a single numeraire have ZERO curl on")
    print("    every triangle, which is what makes departure from it meaningful.")
    rng = np.random.default_rng(1)
    r = rng.normal(size=cx.n_nodes)
    om = np.array([[r[i] - r[j]] for (i, j) in cx.edges], dtype=float)
    pure = [[om[e], np.zeros(1), np.zeros(1)] for e in range(len(cx.edges))]
    c0, _, _, _ = triangle_panels(cx, pure)
    print("    max |c_T| on a pure potential = %.3e" % float(np.abs(c0).max()))
    assert float(np.abs(c0).max()) < 1e-12

    print("(c) THE GATE, SPREAD REGIME. Curl driven by bid-ask jitter, volume drawn")
    print("    independently of spread. The gate must PASS or it can never pass.")
    mc, ms, mv, _ = window_means(curl, spread, invvol, half[0])
    g_ok = gate(mc, ms, mv)
    print("    beta_spread=%+.3f (t=%+.1f)  beta_invvol=%+.3f (t=%+.1f)  ->  %s"
          % (g_ok["beta_spread"], g_ok["t_spread"], g_ok["beta_invvol"],
             g_ok["t_invvol"], g_ok["verdict"]))
    assert g_ok["verdict"] == "PASS", "the gate rejects data it must accept"

    print("(d) THE PLANTED NEGATIVE. Same complex, ZERO spread contribution: every")
    print("    leg sits exactly on the true price but quotes it from up to 60")
    print("    minutes ago, with staleness set by its own activity. The curl here")
    print("    is 100%% microstructure. The gate must VOID it.")
    _, curl_s, spread_s, invvol_s = _synth(regime="stale", seed=3)
    mcs, mss, mvs, _ = window_means(curl_s, spread_s, invvol_s, half[0])
    g_bad = gate(mcs, mss, mvs)
    print("    beta_spread=%+.3f (t=%+.1f)  beta_invvol=%+.3f (t=%+.1f)  ->  %s"
          % (g_bad["beta_spread"], g_bad["t_spread"], g_bad["beta_invvol"],
             g_bad["t_invvol"], g_bad["verdict"]))
    print("    R2 spread-only = %.3f, R2 invvol-only = %.3f"
          % (g_bad["r2_spread_only"], g_bad["r2_invvol_only"]))
    assert g_bad["verdict"] == "VOID", \
        "THE GATE IS DECORATIVE: it passed data whose curl is pure staleness"
    print("    FIRED: staleness-only curl is VOIDed, spread-driven curl PASSes.")

    print("(e) THE DiD RECOVERS A PLANTED RISE AND ONLY A PLANTED RISE.")
    treat = [0, 1, 2]
    for rise, want in ((0.0, False), (6e-4, True)):
        _, cu, sp, iv = _synth(regime="spread", seed=7, treat=treat, rise=rise)
        pre = window_means(cu, sp, iv, half[0])[0]
        post = window_means(cu, sp, iv, half[1])[0]
        d = post - pre
        m = np.array([bool(set(t) & set(treat)) for t in cx.triangles])
        res = did(d[m], d[~m])
        sig = res["lo"] > 0
        print("    rise=%.0e -> DiD %+.3f bp  95%% CI [%+.3f, %+.3f]  n=%d/%d  sig=%s"
              % (rise, res["did"], res["lo"], res["hi"], res["n_treated"],
                 res["n_control"], sig))
        assert sig == want, "the DiD %s a planted effect" % ("missed" if want else "invented")
    print("    FIRED both ways: null is null, planted rise is detected.")

    print("(f) REFUSAL. A group of two is not a group.")
    print("    did([1,2], control) -> %s" % did([1.0, 2.0], np.zeros(50))["verdict"])
    assert did([1.0, 2.0], np.zeros(50))["verdict"] == "REFUSED"
    print("ALL SELF-CHECKS PASSED")


# ---------------------------------------------------------------------------
# The live measurement.

def _groups(cx, nodes):
    """DESTROYED  contains a removed edge: it has no post-cut existence at all.
    SHARED       still stands, but touches an endpoint of some removed edge.
    FAR          touches no endpoint of any removed edge. The far control.
    BASE         the sharp treated set: touches a delisted TOKEN (APT, AR, ...)
                 rather than only a quote hub (BTC, USDC, FDUSD, TRY), which the
                 removals barely dented. SHARED = BASE + HUB-only.
    """
    ix = {a: i for i, a in enumerate(nodes)}
    rem = [(ix[b], ix[q]) for b, q in REMOVED_PAIRS if b in ix and q in ix]
    bases = {ix[b] for b, _ in REMOVED_PAIRS if b in ix}
    touched = set()
    for i, j in rem:
        touched |= {i, j}
    destroyed = np.array([any(i in t and j in t for i, j in rem) for t in cx.triangles])
    shared = np.array([bool(set(t) & touched) for t in cx.triangles]) & ~destroyed
    far = np.array([not (set(t) & touched) for t in cx.triangles])
    base = np.array([bool(set(t) & bases) for t in cx.triangles]) & ~destroyed
    return destroyed, shared, far, base


def _slices():
    def sl(a, b):
        return slice(int((a - GRID_START).total_seconds() // 60),
                     int((b - GRID_START).total_seconds() // 60))
    return dict(real_pre=sl(CUT - WINDOW, CUT), real_post=sl(CUT, CUT + WINDOW),
                pl_pre=sl(PLACEBO_CUT - WINDOW, PLACEBO_CUT),
                pl_post=sl(PLACEBO_CUT, PLACEBO_CUT + WINDOW))


def run():
    print("Listing the bucket (symbols are read, never guessed)...")
    syms = list_symbols()
    keep = {}
    for s in syms:
        p = split_symbol(s)
        if p:
            keep[s] = p
    print("  %d symbols in bucket, %d parse to a quote in %s" % (len(syms), len(keep), str(QUOTES)))

    print("Downloading 1m klines for %s (cache: %s)..." % (", ".join(DAYS), _cache()))
    panel, n_min = load_panel(sorted(keep))
    print("  %d symbols published bars inside the grid" % len(panel))

    edges = []
    for s in panel:
        b, q = keep[s]
        if b != q:
            edges.append((b, q))
    cx, nodes, ix = build_complex(edges)
    print("  %s" % cx)

    sym_of = {}
    for s in panel:
        b, q = keep[s]
        if b == q:
            continue
        i, j = ix[b], ix[q]
        # omega on edge (min,max) is log(price of the LOW-index asset in the high one)
        sym_of[(min(i, j), max(i, j))] = (s, 1.0 if i < j else -1.0)
    series = []
    for e in cx.edges:
        s, sign = sym_of[e]
        a = panel[s]
        series.append([sign * a[0], a[1], a[2]])
    curl, spread, invvol, stale = triangle_panels(cx, series)
    del series

    sl = _slices()
    W = {k: window_means(curl, spread, invvol, v) for k, v in sl.items()}
    live = np.ones(len(cx.triangles), bool)
    for k in W:
        live &= W[k][3] >= MIN_MINUTES
    destroyed, shared, far, base = _groups(cx, nodes)
    print("  triangles: %d total, %d destroyed by a removal, %d with >=%d quoted "
          "minutes in all four windows" % (len(cx.triangles), destroyed.sum(),
                                           live.sum(), MIN_MINUTES))

    print()
    print("=" * 78)
    print("THE GATE  --  pre-intervention window %s to %s UTC"
          % ((CUT - WINDOW).strftime("%m-%d %H:%M"), CUT.strftime("%m-%d %H:%M")))
    print("=" * 78)
    m = live & ~destroyed
    sl_pre = sl["real_pre"]
    print("  zero-trade bars: %.1f%% of all triangle-minutes in the pre window have"
          % (100.0 * stale[m][:, sl_pre].mean()))
    print("  at least one leg whose bar carried NO trades at all.")
    g = None
    for label, drop in (("ALL BARS (the specified gate)", None),
                        ("ZERO-TRADE BARS DROPPED (the rescue attempt)", stale)):
        mc, ms, mv, nmin = window_means(curl, spread, invvol, sl_pre, drop=drop)
        k = m & (nmin >= MIN_MINUTES) & np.isfinite(mc) & np.isfinite(ms) & np.isfinite(mv)
        gg = gate(mc[k], ms[k], mv[k])
        print()
        print("  %s" % label)
        print("    n = %d triangles. Standardized OLS of mean |c_T| on both proxies:" % gg["n"])
        print("      half-spread proxy   beta = %+.3f   t = %+.1f   (R2 alone %.3f, rho %+.3f)"
              % (gg["beta_spread"], gg["t_spread"], gg["r2_spread_only"], gg["rho_spread"]))
        print("      inverse volume      beta = %+.3f   t = %+.1f   (R2 alone %.3f, rho %+.3f)"
              % (gg["beta_invvol"], gg["t_invvol"], gg["r2_invvol_only"], gg["rho_invvol"]))
        print("      joint R2 = %.3f" % gg["r2_joint"])
        print("    VERDICT: %s" % gg["verdict"])
        if g is None:
            g = gg
    print()
    print("=" * 78)
    print("POWER  --  how many triangles each group actually has")
    print("=" * 78)
    live2 = np.ones(len(cx.triangles), bool)
    for kk in sl:
        live2 &= window_means(curl, spread, invvol, sl[kk], drop=stale)[3] >= MIN_MINUTES
    m2 = live2 & ~destroyed
    print("  %-38s %9s %9s" % ("group", "ALL BARS", "TRADED"))
    for nm_, gset in (("shared a node with a removed edge", shared),
                      ("no shared node (the far control)", far),
                      ("touches a delisted TOKEN", base)):
        print("  %-38s %9d %9d" % (nm_, (m & gset).sum(), (m2 & gset).sum()))
    print("  (%d triangles destroyed outright by a removal, excluded from both.)"
          % destroyed.sum())

    print()
    print("=" * 78)
    print("THE CONFOUND IS ITSELF TREATED")
    print("=" * 78)
    tot = np.zeros(4)
    ctl = np.zeros(4)
    order = ["pl_pre", "pl_post", "real_pre", "real_post"]
    dl = {b for b, _ in REMOVED_PAIRS}
    for s, (b, q) in keep.items():
        a = panel.get(s)
        if a is None:
            continue
        v = []
        for kk in order:
            x = a[2][sl[kk]]
            x = x[np.isfinite(x)]
            v.append(float((1.0 / x - 1.0).sum()) if len(x) else np.nan)
        if not np.isfinite(v).all() or v[2] < 50:
            continue
        if b in dl and (b, q) not in REMOVED_PAIRS:
            tot += np.array(v)
        elif b not in dl and q not in dl:
            ctl += np.array(v)
    print("  Trades in the 6h post window over the 6h pre window:")
    print("    surviving pairs of the delisted tokens: placebo %.2fx, cut day %.2fx"
          % (tot[1] / tot[0], tot[3] / tot[2]))
    print("    untouched pairs (the control)         : placebo %.2fx, cut day %.2fx"
          % (ctl[1] / ctl[0], ctl[3] / ctl[2]))
    print("  Flow rerouted onto the surviving edges. That is a real consequence of")
    print("  do(delete edge) -- and it is why the gate cannot be repaired by")
    print("  conditioning on trade arrival: the conditioning variable moves WITH the")
    print("  treatment, in the direction that mechanically lowers measured curl.")

    if g["verdict"] != "PASS":
        print()
        print("  |c_T| tracks 1/volume rather than spread. The curl this pipeline")
        print("  would measure is asynchronous quoting, not arbitrage residual, so")
        print("  the before/after comparison is VOID and is not run.")
        return g

    print()
    print("=" * 78)
    print("BEFORE / AFTER  --  mean |c_T| in basis points")
    print("=" * 78)
    out = {"gate": g}
    for tag, cut, pre, post in (("REAL    (cut 08-14 03:00 UTC)", CUT, "real_pre", "real_post"),
                                ("PLACEBO (fake cut 08-13 03:00 UTC)", PLACEBO_CUT, "pl_pre", "pl_post")):
        d = W[post][0] - W[pre][0]
        print("\n%s" % tag)
        for name, g_ in (("shared a node", shared), ("no shared node (far control)", far),
                         ("delisted TOKEN only", base)):
            k = m & g_
            print("  %-30s n=%4d  pre %8.2f  post %8.2f  delta %+8.2f"
                  % (name, k.sum(), np.nanmean(W[pre][0][k]), np.nanmean(W[post][0][k]),
                     np.nanmean(d[k])))
        for label, tr in (("shared-vs-far", shared), ("token-vs-far", base)):
            r = did(d[m & tr][np.isfinite(d[m & tr])], d[m & far][np.isfinite(d[m & far])])
            out["%s_%s" % (post.split("_")[0], label)] = r
            if r["verdict"] != "OK":
                print("  DiD %-14s REFUSED (n=%d/%d)" % (label, r["n_treated"], r["n_control"]))
            else:
                print("  DiD %-14s %+8.3f bp   95%% CI [%+.3f, %+.3f]   t=%+.1f"
                      % (label, r["did"], r["lo"], r["hi"], r["t"]))
    print()
    print("The placebo DiD is the diurnal floor: any real effect must clear it.")
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--selfcheck", action="store_true",
                    help="offline synthetic check, including the planted negative")
    a = ap.parse_args()
    selfcheck() if a.selfcheck else run()


if __name__ == "__main__":
    main()
