"""THEORY.md §1 constraint 2 ("Make P a transition kernel: row-stochastic, non-negative")
and §8 risk 5 ("Stochastic P may destroy expressiveness").

THEORY.md calls the row-stochastic constraint free: "two constraints on an existing,
working, tested solve -- not a new architecture", and argues the contraction
certificate becomes structural rather than measured. The certificate claim is true.
These tests ask what it costs.

Three separate things are attacked:

  A. The output range. Row-stochastic P forces (I - gamma P)^-1 to be non-negative
     with every row summing to 1/(1-gamma). z = M b is therefore a CONVEX COMBINATION
     of b's entries, scaled by 1/(1-gamma). No choice of P and no choice of gamma can
     produce a z outside [min(b), max(b)]/(1-gamma). This is not a tightness question;
     it is a closed hypothesis class.

  B. Enforcement cost per step. If the constraint is imposed by Euclidean projection
     onto the simplex (the option that keeps sigmoid's existing ridge fit), what does
     the projection do to the gradient, and are the zeros it creates recoverable?

  C. What the solve costs at 1B scale, since gamma explicit + P stochastic still
     leaves a dense d x d solve in the forward pass.
"""

import os
import sys
import time

import pytest
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from theory_ref import project_rows_to_simplex, resolvent, rows_softmax  # noqa: E402

# Was `torch.set_default_dtype(torch.float64)` at module scope. pytest imports
# every test module during COLLECTION, so that ran before any test did and leaked
# float64 into every other module in the process -- measured: it broke
# test_kernel_contracts.py::test_residual_path_masks_the_missing_backward with
# "expected mat1 and mat2 to have the same dtype, but got: float != double",
# and it did so only for some `-k` filters, because it depended on collection
# order. Scoped to this module instead.
@pytest.fixture(autouse=True, scope="module")
def _float64_for_this_module():
    prev = torch.get_default_dtype()
    torch.set_default_dtype(torch.float64)
    yield
    torch.set_default_dtype(prev)


# ============================================== A. the convex-hull expressiveness ceiling

def test_resolvent_output_can_leave_the_convex_hull_of_b():
    """Fit the best possible (gamma, P) to a target that an unconstrained A reaches easily.

    Target is generated by an ORDINARY unconstrained operator -- exactly what
    sigmoid §5 fits today and what its measured numbers were obtained with.
    """
    torch.manual_seed(0)
    d = 32
    A_true = torch.randn(d, d)
    A_true *= 0.9 / torch.linalg.eigvals(A_true).abs().max().real   # rho = 0.9, well posed
    b = torch.rand(d)                                               # b in [0, 1]
    z_target = torch.linalg.solve(torch.eye(d) - A_true, b)

    logits = torch.zeros(d, d, requires_grad=True)
    g_raw = torch.zeros(1, requires_grad=True)                      # gamma = sigmoid(g_raw)
    opt = torch.optim.Adam([logits, g_raw], lr=0.05)
    for _ in range(3000):
        opt.zero_grad()
        gamma = torch.sigmoid(g_raw).clamp(1e-4, 1 - 1e-6)
        P = rows_softmax(logits)
        z = torch.linalg.solve(torch.eye(d) - gamma * P, b)
        loss = ((z - z_target) ** 2).mean()
        loss.backward()
        opt.step()

    gamma = float(torch.sigmoid(g_raw).clamp(1e-4, 1 - 1e-6))
    z = resolvent(rows_softmax(logits).detach(), gamma, b)
    nrmse = float((z - z_target).norm() / z_target.norm())
    lo, hi = float(b.min()) / (1 - gamma), float(b.max()) / (1 - gamma)
    outside = int(((z_target < lo) | (z_target > hi)).sum())

    assert nrmse < 0.10, (
        f"best-fit stochastic P reaches NRMSE {nrmse:.3f} against a target an "
        f"unconstrained A produces exactly. gamma converged to {gamma:.4f}; the "
        f"reachable set is [{lo:.3f}, {hi:.3f}] and {outside}/{d} target coordinates "
        f"lie outside it. No (P, gamma) can fix this: M is non-negative with row sums "
        f"1/(1-gamma), so z is a scaled convex combination of b."
    )


def test_reachable_set_is_not_a_scaled_convex_hull():
    """The structural statement behind the test above, checked directly."""
    torch.manual_seed(1)
    d = 16
    b = torch.rand(d)
    for gamma in (0.5, 0.9, 0.99):
        for trial in range(200):
            P = rows_softmax(torch.randn(d, d) * 3.0)
            z = resolvent(P, gamma, b)
            lo, hi = b.min() / (1 - gamma), b.max() / (1 - gamma)
            assert (z >= lo - 1e-9).all() and (z <= hi + 1e-9).all(), "hull violated"
    pytest.fail(
        "200 random stochastic P at each of gamma in {0.5, 0.9, 0.99}: every output "
        "coordinate stayed inside [min(b), max(b)]/(1-gamma). The resolvent cannot "
        "extrapolate beyond its input's range. THEORY.md §1 claims the constraint "
        "'does not misreport anything' -- it does not misreport, it cannot report."
    )


# ================================================ B. what enforcing the constraint costs

def test_simplex_projection_preserves_gradient_direction():
    """Projection is not free: its Jacobian annihilates a direction per row and
    zeroes entries outside the active set."""
    torch.manual_seed(2)
    d = 64
    A = torch.randn(d, d, requires_grad=True)
    P = project_rows_to_simplex(A)
    g = torch.randn(d, d)
    (P * g).sum().backward()

    kept = float(A.grad.norm() / g.norm())
    dead = float((P == 0).double().mean())
    assert kept > 0.95 and dead < 0.05, (
        f"projection destroyed {100 * (1 - kept):.1f}% of the gradient norm in a single "
        f"step and left {100 * dead:.1f}% of P's entries exactly zero. Entries at zero "
        f"whose gradient points further negative receive no gradient at all."
    )


def test_projected_entries_can_recover():
    """A zeroed entry must be able to come back, or the hypothesis class shrinks
    monotonically over 40k steps."""
    torch.manual_seed(3)
    d = 32
    A = (torch.randn(d, d) * 0.5).requires_grad_()
    opt = torch.optim.Adam([A], lr=1e-2)
    target = rows_softmax(torch.randn(d, d) * 2.0)
    trace = []
    for step in range(2000):
        opt.zero_grad()
        P = project_rows_to_simplex(A)
        loss = ((P - target) ** 2).mean()
        loss.backward()
        opt.step()
        if step % 100 == 0:
            trace.append((step, float((project_rows_to_simplex(A) == 0).double().mean()),
                          float(loss)))
    zeros = [t[1] for t in trace]
    assert zeros[-1] <= zeros[len(zeros) // 4] + 0.02, (
        "dead-entry fraction over training: "
        + ", ".join(f"step {s}: {z:.1%} zero (loss {l:.2e})" for s, z, l in trace[::4])
        + ". The support only shrinks."
    )


# ============================================================== C. cost of the solve

def test_resolvent_solve_is_cheap_at_1b_scale():
    """A 1B model has d ~ 2048. THEORY.md §6 puts one resolvent solve in the pipeline.
    Row-stochastic P via softmax is DENSE, so this is a dense d x d solve."""
    d = 2048
    from _chase_env import HAS_CUDA
    dev = "cuda" if HAS_CUDA else "cpu"
    P = rows_softmax(torch.randn(d, d, device=dev, dtype=torch.float32))
    b = torch.randn(d, 1, device=dev, dtype=torch.float32)
    I = torch.eye(d, device=dev, dtype=torch.float32)
    for _ in range(3):
        torch.linalg.solve(I - 0.99 * P, b)
    if dev == "cuda":
        torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(20):
        torch.linalg.solve(I - 0.99 * P, b)
    if dev == "cuda":
        torch.cuda.synchronize()
    per_solve_ms = (time.perf_counter() - t0) / 20 * 1e3

    # An attention layer at d=2048, seq=2048 is ~2*2048*2048*2048*2 = 34 GFLOP.
    # A dense LU solve at d=2048 is ~2/3 d^3 = 5.7 GFLOP. Budget: 5% of a layer.
    assert per_solve_ms < 0.5, (
        f"dense resolvent solve at d={d} costs {per_solve_ms:.2f} ms on {dev} "
        f"(~{2 / 3 * d ** 3 / 1e9:.1f} GFLOP), per layer, per forward. P is dense "
        f"because softmax rows are dense; the sparsity in THEORY.md lives in the "
        f"attention schedule, not here."
    )
