"""BED-K and the interventional channel -- CEQ_V15_CONTRACT.md PART III.

BED-K's whole reason to exist is that every corpus in the campaign up to this
file is Markov-generated (WHERE WE ARE: "no label has ever contained a
delayed cause"). That is a claim about the LABEL's dependency structure, and
a claim about dependency structure is not established by eyeballing a
formula -- it has to be measured against an instrument that could, in
principle, find the opposite answer. Every test below is built so a broken
`ceq/beds/bed_k.py` fails it:

  1. scan-blindness is measured, not asserted, and paired with an AR(1)
     control so a fit routine that is simply broken (always reads R^2~0)
     cannot hide behind "well, scan-blind was expected anyway" -- MISTAKES.md
     V-8, "the PASS half's label is constant."
  2. attention-reachability is a real reconstruction, not a claim.
  3. the Hurst estimator ships with the white-noise must-fire the contract
     names by clause, plus the AR(0.5) reading the contract warns is where
     R/S (not this estimator) reads 0.75 and is wrong.
  4. the Jacobian oracle is checked against an INDEPENDENT recomputation
     (`bed_k.rebuild`, which never calls `bed_k.bump`), not against itself.
  5. every bump is checked to move the label where the kernel says it
     should, AND to leave it bitwise untouched where the kernel is zero --
     MISTAKES.md V-9, "a repair that changes nothing," has a live twin here:
     a do()-bit that moves nothing would be exactly that pattern.
  6. reproducibility is checked both ways: same seed matches, different seed
     differs. A generator that ignores its seed entirely would pass a
     same-seed-only check.

Run order: this file is authored, and shown red, BEFORE `ceq/beds/bed_k.py`
exists (V15_N4_BEDK.md carries that transcript). Every numeric threshold
below is justified in its own docstring or comment, not chosen after seeing
what passes -- most are backed by a scratch measurement cited inline.
"""
from __future__ import annotations

import numpy as np
import pytest

from ceq.beds import bed_k


def _ar1(n: int, phi: float, seed: int) -> np.ndarray:
    """A genuine AR(1): w_i = phi*w_{i-1} + eps_i. Used only as a control
    series (never as a bed), so it lives here rather than in bed_k.py."""
    rng = np.random.default_rng(seed)
    eps = rng.standard_normal(n)
    w = np.zeros(n)
    for t in range(1, n):
        w[t] = phi * w[t - 1] + eps[t]
    return w


# ---------------------------------------------------------------------------
# 1. delay bed is scan-blind, AR(1) control confirms the fit routine works
# ---------------------------------------------------------------------------


def test_delay_bed_scan_blind_but_ar1_control_reaches_0_99():
    """Fits y_i = alpha*y_{i-1} + beta*x_i by least squares, giving the
    recurrence the MOST generous possible state: the delay bed's own true
    previous label (a real scan only has its own prior output, never ground
    truth), so a low R^2 here cannot be blamed on a weak state proxy.

    Why 0.05. `b` is iid, so z_{i-1} = b_{i-1-d} and z_i = b_{i-d} are drawn
    from different, independent positions of the SAME noise for any d >= 1 --
    population R^2 is exactly 0, not approximately 0. The finite-sample noise
    floor with p=2 regressors at n=2048 is ~p/(n-1) ~ 0.001; measured
    directly over 30 seeds at d=4 it was [-0.0027, 0.0028]. 0.05 is ~18x that
    measured ceiling and a two-order-of-magnitude margin below the AR(1)
    control's 0.99, so the two halves cannot be confused by threshold choice.
    """
    n, d, seed = 2048, 5, 0
    bed = bed_k.build_delay(n, d, seed)
    z, b = bed["z"][d:], bed["b"][d:]
    _, _, r2_delay = bed_k.fit_first_order_recurrence(z, b)

    THRESH = 0.05
    assert r2_delay < THRESH, (
        f"first-order recurrence explains the delay label (R2={r2_delay}); "
        "the delay bed is not scan-blind at d={d}"
    )

    # V-8's rule: check the PASS half's label is non-degenerate before the
    # FAIL half is interesting. Here that means showing the FIT ITSELF can
    # reach a high R2 on data actually generated by this recurrence form --
    # otherwise a low R2 above just means "the lstsq call is broken."
    a_true = 0.8
    rng = np.random.default_rng(seed + 1)
    eps = rng.standard_normal(n)
    w = np.zeros(n)
    for t in range(1, n):
        w[t] = a_true * w[t - 1] + eps[t]
    alpha_hat, beta_hat, r2_ar1 = bed_k.fit_first_order_recurrence(w, eps)
    assert r2_ar1 >= 0.99, (
        f"fit routine reaches only R2={r2_ar1} on a true AR(1) series "
        f"(alpha_hat={alpha_hat}, beta_hat={beta_hat}); it is too weak for "
        "the scan-blind reading above to mean anything"
    )


# ---------------------------------------------------------------------------
# 2. delay bed is attention-reachable
# ---------------------------------------------------------------------------


def test_delay_bed_is_attention_reachable_to_1e_12():
    """A single hand-set attention head -- one-hot positional query/key coding
    offset by d, fixed temperature -- reproduces the delay label for i >= d
    (i < d has no valid source position; the label itself is undefined
    there, so callers do not compare it).

    Precision bound: softmax residual off the true position is bounded by
    (n-1)*exp(-temperature). At temperature=45, n=500: 499*exp(-45) ~ 1.3e-17,
    far under the 1e-12 the must-fire asks for. Measured directly: max abs
    error 8.67e-19 at n=500, d=4 (scratch run backing this test).
    """
    n, d, seed = 500, 7, 3
    bed = bed_k.build_delay(n, d, seed)
    # Read ONLY the two fields build()'s manifest actually exposes (`b` and
    # `pos`) -- not `bed["K"]`. A delay is a POSITIONAL operation, so passing
    # `pos` explicitly (rather than letting the head assume index order) is
    # what makes this a claim about a channel a real arm could also read,
    # per the coordinator's cross-node finding: an arm given content only,
    # no positional feature, would fail this bed for a reason that has
    # nothing to do with memory kernels, and the two failure causes must not
    # be allowed to collapse into one number.
    pred = bed_k.hard_delay_attention(bed["b"], d, pos=bed["pos"])
    err = float(np.max(np.abs(pred[d:] - bed["z"][d:])))
    assert err <= 1e-12, f"attention head does not reproduce the delay label: max err={err}"


# ---------------------------------------------------------------------------
# 3. power-law bed's Hurst covariate, with the white-noise and AR(0.5)
#    must-fires the contract names by clause
# ---------------------------------------------------------------------------


def test_hurst_estimator_white_noise_must_fire():
    """CEQ_V15_CONTRACT.md PART III: "the Hurst covariate ships ONLY with its
    white-noise must-fire." White noise has true H=0.5 and no long-range
    structure at all; this is the estimator's null case.

    Averaged over 5 seeds (n=8192 each) to keep the check from being a
    single noisy draw -- MISTAKES.md M-4 warns against reading single-seed
    variability as if it were the truth. Tolerance 0.15 measured directly:
    5-seed means across two independent seed blocks (0-4 and repeats) landed
    at 0.477-0.513, i.e. within 0.05 of 0.5 both times.
    """
    n = 8192
    ests = [bed_k.estimate_hurst_dfa(np.random.default_rng(seed).standard_normal(n))
            for seed in range(5)]
    h_hat = float(np.mean(ests))
    assert abs(h_hat - 0.5) < 0.15, f"DFA reads H={h_hat} on white noise (true H=0.5): {ests}"


def test_hurst_estimator_ar05_is_not_the_rs_bias():
    """CEQ_V15_CONTRACT.md PART III, verbatim: "the author's R/S read 0.75 on
    AR(0.5): biased." AR(0.5) is short-memory only (true H=0.5); R/S reads it
    high. This is the must-fire that an estimator claiming to be calibrated
    has to pass: report the SAME estimator's reading on this EXACT case and
    require it nowhere near the biased value.

    0.65 sits at the midpoint between the unbiased truth (0.5) and R/S's
    documented failure (0.75) -- closer to either would make the threshold
    do the work instead of the estimator.
    """
    n = 8192
    ests = [bed_k.estimate_hurst_dfa(_ar1(n, 0.5, seed)) for seed in range(5)]
    h_hat = float(np.mean(ests))
    assert h_hat < 0.65, (
        f"DFA reads H={h_hat} on AR(0.5) -- inside R/S's documented biased "
        f"range (0.75); this estimator is not the calibrated one the "
        f"contract asks for: {ests}"
    )


def test_hurst_estimator_recovers_known_H_on_the_powerlaw_bed():
    """Generate at a known H, estimate it back. n=8192, H=0.75, 5 seeds
    (100-104, a different block from the white-noise/AR(0.5) seeds above so
    this is not the same draws re-used). Tolerance 0.15 measured directly:
    mean H_hat=0.812 on this exact seed block (bias +0.062); a second,
    independent seed block (0-4) gave mean 0.787 (bias +0.037). Both well
    inside 0.15 with room to spare; a broken kernel (wrong sign on the
    exponent, off-by-one in the causal mask, or H substituted for 1-H) reads
    far outside it -- e.g. H_hat~0.5 for an accidentally-white kernel.
    """
    n, H_true, seed0 = 8192, 0.75, 100
    ests = []
    for i in range(5):
        bed = bed_k.build_powerlaw(n, H_true, seed=seed0 + i)
        ests.append(bed_k.estimate_hurst_dfa(bed["z"]))
    h_hat = float(np.mean(ests))
    assert abs(h_hat - H_true) < 0.15, f"H_hat={h_hat} vs H_true={H_true}: {ests}"


# ---------------------------------------------------------------------------
# 3b. the stationarity box is enforced, not just documented
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("H", [0.3, 0.5, 1.0, 1.2])
def test_powerlaw_bed_refuses_outside_the_stationarity_box(H):
    """CEQ_V15_CONTRACT.md's power-law clause states H > 0.5 with no upper
    bound; ARFIMA(0, d, 0) with d = H - 1/2 is finite-variance/stationary
    only for |d| < 0.5, i.e. H strictly in (0.5, 1.0). H=0.5 (white noise,
    excluded by the contract's own '>') and H=1.0 (alpha=0.5, the boundary
    where GL weight energy stops being square-summable) must both raise --
    the box is closed on both ends, not just the one the contract wrote out.
    A generator that silently built a corpus at H=1.0 would hand H-recovery
    a label with no population Hurst exponent to recover.
    """
    with pytest.raises(ValueError):
        bed_k.build_powerlaw(64, H, seed=0)


def test_powerlaw_bed_builds_inside_the_stationarity_box():
    """V-8's rule, applied to a refusal: a gate that rejects everything is as
    vacuous as one that accepts everything. Confirms the box has a non-empty
    interior on the SAME code path as the refusal test above."""
    bed = bed_k.build_powerlaw(64, 0.75, seed=0)
    assert bed["z"].shape == (64,)
    assert np.all(np.isfinite(bed["z"]))


# ---------------------------------------------------------------------------
# 4. Jacobian oracle is exact on both beds
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("kind,params", [("delay", dict(d=4)), ("powerlaw", dict(H=0.75))])
def test_jacobian_oracle_matches_independent_finite_difference(kind, params):
    """`bump` reads the analytic Jacobian column straight off the kernel;
    `finite_diff_jacobian_column` recomputes it via `bed_k.rebuild` (the
    generator's own forward pass) at a central difference, eps=1e-6,
    float64. `bump` never calls `rebuild` and `finite_diff_jacobian_column`
    never reads `bed["K"]` directly -- two independent routes to the same
    number, which is what makes the agreement a check rather than an
    identity (MISTAKES.md V-3).

    z = K @ b is exactly linear in b, so central-difference truncation error
    is zero in exact arithmetic; the only error source is float64 rounding,
    orders of magnitude under 1e-9.
    """
    n, seed = 300, 0
    bed = bed_k.build(kind, n, seed, **params)
    eps = 1e-6
    max_err = 0.0
    for p in (0, 1, n // 3, n // 2, n - 2, n - 1):
        analytic = bed_k.bump(bed, p, eps)
        fd = bed_k.finite_diff_jacobian_column(bed, p, eps)
        max_err = max(max_err, float(np.max(np.abs(analytic - fd))))
    assert max_err <= 1e-9, f"{kind}: analytic vs finite-diff Jacobian differ by {max_err}"


# ---------------------------------------------------------------------------
# 5. the bumps actually move the label -- both halves
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("kind,params", [("delay", dict(d=4)), ("powerlaw", dict(H=0.75))])
def test_bump_moves_z_exactly_where_kernel_nonzero_and_nowhere_else(kind, params):
    """MISTAKES.md V-9: "a repair that changes nothing." A do()-bit that
    moves the label by exactly 0.0 everywhere is that pattern wearing an
    interventional-channel costume, and `tests/loop/test_every_boundary_
    node_can_propagate.py` already has a live instance of it -- this is the
    same check, run against BED-K's own bump.

    Both halves are required (V-8's non-degeneracy rule, restated for a
    boolean mask rather than a class label): the nonzero set must be neither
    empty nor everything, checked directly, or the two assertions below have
    no content.
    """
    n, seed = 200, 0
    bed = bed_k.build(kind, n, seed, **params)
    p = n // 2
    eps = 1e-3
    b2 = bed["b"].copy()
    b2[p] += eps
    z2 = bed_k.rebuild(bed, b2)
    diff = z2 - bed["z"]

    nonzero_mask = bed["K"][:, p] != 0.0
    assert 0 < int(nonzero_mask.sum()) < n, (
        f"{kind}: kernel column p={p} is degenerate (all-zero or all-nonzero); "
        "this test would have no discriminating power"
    )
    assert np.all(diff[nonzero_mask] != 0.0), f"{kind}: bump did not move z where K != 0"
    assert np.all(diff[~nonzero_mask] == 0.0), f"{kind}: bump moved z where K == 0 (not exact)"


# ---------------------------------------------------------------------------
# 6. seeded reproducibility
# ---------------------------------------------------------------------------


def test_seeded_reproducibility_both_beds():
    d1 = bed_k.build_delay(500, 4, seed=7)
    d2 = bed_k.build_delay(500, 4, seed=7)
    assert np.array_equal(d1["b"], d2["b"])
    assert np.array_equal(d1["z"], d2["z"])
    d3 = bed_k.build_delay(500, 4, seed=8)
    assert not np.array_equal(d1["b"], d3["b"])
    assert not np.array_equal(d1["z"], d3["z"])

    p1 = bed_k.build_powerlaw(500, 0.75, seed=7)
    p2 = bed_k.build_powerlaw(500, 0.75, seed=7)
    assert np.array_equal(p1["b"], p2["b"])
    assert np.array_equal(p1["z"], p2["z"])
    p3 = bed_k.build_powerlaw(500, 0.75, seed=8)
    assert not np.array_equal(p1["b"], p3["b"])
    assert not np.array_equal(p1["z"], p3["z"])
