"""A boundary node with no interior neighbour is a do()-bit with no consequence.

THE DEFECT. `scale/r10_corpus_spec.py::admissible` — JUPITER's Amendment (A) —
guards one direction of the boundary/interior relation and not the other:

    "no isolated vertex, `B` non-empty, and every interior vertex able to reach `B`"

That is exactly the condition for `(I - P_II)` to be invertible: `rho(P_II) < 1`
iff every interior state escapes to the boundary. It is necessary and it is
checked.

**The mirror direction is not checked.** Nothing requires a BOUNDARY vertex to
have an INTERIOR neighbour. A boundary node all of whose neighbours are also
boundary nodes leaves the resolvent perfectly invertible — it simply influences
nothing. Intervening on it cannot propagate, because there is no interior vertex
adjacent to it to propagate into.

MEASURED, MARS at iteration 17: `reproduce-n1024-d4-t0.95`, seed `0x3a14000a`,
ships exactly such a node, and its do()-bit moves the label by **exactly 0.0 in
every norm**. One instance of twelve, at the corpus's LARGEST boundary
(`|B| = 80`), which is where it should be expected — the more boundary nodes a
graph carries, the likelier some boundary node sees only boundary.

WHY IT MATTERS BEYOND ONE INSTANCE. This corpus exists to measure causal
consequence. An instance where a causal intervention has no consequence is not a
hard case; it is a case the task's own premise excludes, generated by the builder
because nothing forbade it. C-F's clause reads `fd >= delta` for a pre-set delta,
so a reading of exactly 0.0 fails **any** positive threshold — which is why this
finding survives the strike against C-F's delta (imported out of its units from
the chain task, unreachable for `|B| > 7.5`; see MISTAKES.md V-17). Threshold-free
findings outlive threshold disputes.

THE ROUTE. One clause in `admissible`, the mirror of the one already there:

    every b in B has at least one neighbour not in B

It is Amendment (B) to the same function, it costs one pass over the adjacency,
and it rejects at generation time rather than at measurement time. The corpus then
needs regenerating — which is why this guard is RED rather than the fix being
applied here: the twelve rungs already measured were measured on the corpus as it
is, and silently changing the generator underneath published readings is the
worse error.

SCOPE. This reads MARS's shipped census rather than regenerating the corpus,
because the census carries `boundary_nodes_with_no_interior_neighbour` per
instance and regenerating would re-derive a number that already exists. If that
file is absent the guard SKIPS with a stated reason rather than passing.
"""
from __future__ import annotations

import json
import pathlib

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]
CENSUS = ROOT / "results" / "r10_it17_battery.jsonl"
FIELD = "boundary_nodes_with_no_interior_neighbour"


def census_rows() -> list[dict]:
    """The C-F rows that carry the count, corpus instances only."""
    if not CENSUS.exists():
        return []
    out = []
    for line in CENSUS.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            r = json.loads(line)
        except json.JSONDecodeError:
            continue
        if r.get("kind") == "C-F-a" and FIELD in r:
            out.append(r)
    return out


def corpus_rows() -> list[dict]:
    """Corpus instances, excluding the deliberate plants."""
    return [r for r in census_rows() if not str(r.get("id", "")).startswith("plant-")]


def test_the_census_exists_and_carries_the_field():
    """Must-fire for this file's own reader. With no rows every assertion below
    passes by vacuity, which is the shape MISTAKES.md V-7 records."""
    if not CENSUS.exists():
        pytest.skip(f"{CENSUS.name} absent; the census has not been run here")
    rows = census_rows()
    assert rows, (
        f"{CENSUS.name} exists but carries no C-F-a row with {FIELD!r}; this guard "
        "is reading the wrong file or the wrong field and would pass on nothing"
    )
    assert len(corpus_rows()) >= 12, (
        f"only {len(corpus_rows())} corpus instances in the census; the twelve "
        "stratified rungs are the population this guard rules on"
    )


def test_the_reader_separates_the_plants_from_the_corpus():
    """Must-not-fire. The census includes DELIBERATE plants -- `plant-dead-bit`
    carries the defect on purpose. Counting them as corpus instances would make
    the guard fire on its own control and report a defect that was planted."""
    planted = [r for r in census_rows() if str(r.get("id", "")).startswith("plant-")]
    assert planted, "no plant rows found; the separation below is untested"
    assert all(not str(r.get("id", "")).startswith("plant-") for r in corpus_rows())


def test_the_plant_carries_the_defect_so_the_count_can_be_nonzero():
    """Must-fire: the field must be able to read non-zero, or a corpus reading of
    zero would carry no information."""
    if not CENSUS.exists():
        pytest.skip("census absent")
    planted = [r for r in census_rows() if str(r.get("id", "")).startswith("plant-")]
    assert any(r.get(FIELD, 0) > 0 for r in planted), (
        f"no planted instance reads {FIELD} > 0, so a corpus reading of 0 cannot be "
        "distinguished from a counter that never fires"
    )


@pytest.mark.parametrize("row", corpus_rows() or [None],
                         ids=lambda r: (r or {}).get("id", "no-census"))
def test_no_corpus_instance_has_a_boundary_node_that_cannot_propagate(row):
    """THE DEFECT, one case per instance so a repair reads as a partial pass."""
    if row is None:
        pytest.skip("census absent; nothing to rule on")
    n = row.get(FIELD, 0)
    assert n == 0, (
        f"{row.get('id')} (seed {row.get('seed')}, |B|={row.get('boundary_size')}) "
        f"has {n} boundary node(s) with NO interior neighbour, so a do() on such a "
        f"node cannot propagate: measured fd exactly 0.0 in every norm. "
        f"`r10_corpus_spec.admissible` checks the MIRROR condition -- every "
        f"interior vertex reaches B, which is what makes (I - P_II) invertible -- "
        f"and nothing checks that every boundary vertex has an interior neighbour. "
        f"A corpus for causal consequence emitted an instance where a causal "
        f"intervention has none. Route: add the mirror clause to `admissible` "
        f"(every b in B has a neighbour outside B) and regenerate; this is RED "
        f"rather than fixed because the twelve measured rungs were measured on the "
        f"corpus as it stands."
    )
