# K2 identity grid on Kaggle (Wilson, Phase K it.K2). Generated by mk_kernels.py; the payload below is the whole input.
# 1. writes every source file byte-identical under /tmp/sp (the scratchpad copy) and under the cwd copy of the repo
#    paths, checks each sha256 against the registered one (abort on any mismatch);
# 2. checks Cameron's bed fingerprints (numpy stream; abort on any mismatch);
# 3. runs the lanes, one per GPU, concurrently; each job's stdout to <runs>/<name>.stdout, hardware.json in its run dir;
#    walk jobs run right after their fR training job in the same lane; model.pt kept only where keep_model;
# 4. status in /kaggle/working/kernel_status.json.
import base64, hashlib, json, os, platform, subprocess, sys, threading, time
from pathlib import Path
T0 = time.time()
CFG = json.loads(base64.b64decode(PAYLOAD).decode())
SPK = Path("/tmp/sp")
CWD = SPK / "phase_k" / "K2" / "cameron"
W = Path("/kaggle/working")
REPO_REL = "C:/Users/seal/Desktop/New folder (32)"
ST = {"slug": CFG["slug"], "version_expected": CFG["version"], "t0": time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime(T0)) + "Z",
      "sha": {}, "fp": {}, "jobs": {}}
LOCK = threading.Lock()


def save():
    with LOCK:
        (W / "kernel_status.json").write_text(json.dumps(ST, indent=1))


def die(reason):
    ST["abort"] = reason
    save()
    print("ABORT", reason, flush=True)
    sys.exit(2)


sha = lambda b: hashlib.sha256(b).hexdigest()
for rel, e in CFG["files"].items():
    p = (CWD / REPO_REL / rel[5:]) if rel.startswith("REPO/") else (SPK / rel)
    p.parent.mkdir(parents=True, exist_ok=True)
    data = base64.b64decode(e["b64"])
    p.write_bytes(data)
    got = sha(p.read_bytes())
    ST["sha"][rel] = {"expected": e["sha"], "on_disk": got, "ok": got == e["sha"] == sha(data), "path": str(p)}
    print(("SHA OK   " if ST["sha"][rel]["ok"] else "SHA FAIL ") + rel + " " + got, flush=True)
if not all(v["ok"] for v in ST["sha"].values()):
    die("sha mismatch")
for d in ("runs", "runs_kaggle_control"):
    (W / d).mkdir(parents=True, exist_ok=True)
    (CWD / d).symlink_to(W / d, target_is_directory=True)

# bed fingerprints (mk_jobs_remaining.py's fp, copied)
import numpy as np
sys.path.insert(0, str(SPK / "phase_k" / "K1" / "cameron"))
import bed_kp


def fp(beds):
    h = hashlib.sha256()
    for b in beds:
        for key in ("ids", "pids", "target", "depth", "root"):
            h.update(np.ascontiguousarray(b[key], dtype=np.int64).tobytes())
    return h.hexdigest()


got = {f"far10_n{n}": fp([bed_kp.make_test(np.random.default_rng([31, n, kk]), n) for kk in range(8)]) for n in (4096, 8192, 16384)}
got["heldout_1024"] = fp([bed_kp.make_train(np.random.default_rng([21, kk])) for kk in range(64)])
ns = (256, 512, 1024, 2048, 4096)
for s in (0, 1, 2):
    bs = []
    for step in range(1, 6):
        rng = np.random.default_rng([1000 + s, step]); n = ns[step % 5]
        bs += [bed_kp.make_train(rng, n=n) for _ in range(8192 // n)]
    got[f"train_seed{s}_steps1-5"] = fp(bs)
for k, v in CFG["fps"].items():
    ST["fp"][k] = {"expected": v, "got": got.get(k), "ok": got.get(k) == v}
    print(("FP OK   " if ST["fp"][k]["ok"] else "FP FAIL ") + k, flush=True)
if not all(v["ok"] for v in ST["fp"].values()):
    die("bed fingerprint mismatch")

import torch
NG = torch.cuda.device_count()
drv = subprocess.run(["nvidia-smi", "--query-gpu=index,name,driver_version,memory.total", "--format=csv,noheader"],
                     capture_output=True, text=True).stdout.strip()
HW = {"torch": torch.__version__, "cuda": torch.version.cuda, "cudnn": torch.backends.cudnn.version(), "python": platform.python_version(),
      "numpy": np.__version__, "gpu_count": NG, "nvidia_smi": drv, "kernel_slug": CFG["slug"], "kernel_version_expected": CFG["version"],
      "kernel_run_type": os.environ.get("KAGGLE_KERNEL_RUN_TYPE"),
      "bf16_supported": bool(NG and torch.cuda.is_bf16_supported())}
ST["hw"] = HW
save()
print(json.dumps(HW), flush=True)
if NG == 0:
    die("no GPU")
LANES = CFG["lanes"] if NG >= 2 else [[j for lane in CFG["lanes"] for j in lane]]
SOFT, HARD = CFG["soft_s"], CFG["hard_s"]


def run_lane(gi, jobs):
    env = dict(os.environ, CUDA_VISIBLE_DEVICES=str(gi), PYTHONDONTWRITEBYTECODE="1")
    failed = set()
    for j in jobs:
        name, out = j["name"], Path(j["out"])
        rec = {"lane": gi, "gpu": torch.cuda.get_device_name(gi), "kind": j["kind"]}
        el = time.time() - T0
        if j.get("after") in failed:
            rec["status"] = "skipped: training job failed"
        elif el + j["est_s"] > SOFT:
            rec["status"] = f"skipped: elapsed {el:.0f} s + estimate {j['est_s']:.0f} s > soft limit {SOFT:.0f} s"
        if "status" in rec:
            failed.add(name)
            with LOCK:
                ST["jobs"][name] = rec
            save()
            continue
        out.mkdir(parents=True, exist_ok=True)
        hw = {**HW, "gpu_name": rec["gpu"], "gpu_index_in_kernel": gi, "job": name,
              "started_utc": time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime())}
        if j["kind"] != "walk":
            (out / "hardware.json").write_text(json.dumps(hw, indent=1))
        t = time.time()
        rec["start_s"] = t - T0
        with LOCK:
            ST["jobs"][name] = {**rec, "status": "running"}
        save()
        print(f"{time.strftime('%H:%M:%S')} lane {gi} start {name}", flush=True)
        try:
            with open(out.parent / f"{name}.stdout", "a") as f:
                rc = subprocess.run([sys.executable] + j["argv"][1:], cwd=CWD, env=env, stdout=f, stderr=subprocess.STDOUT,
                                    timeout=max(60.0, HARD - (time.time() - T0))).returncode
        except subprocess.TimeoutExpired:
            rc = "timeout"
        rec.update(rc=rc, wall_s=time.time() - t, status="done" if rc == 0 else "failed")
        if rc != 0:
            failed.add(name)
        if j["kind"] == "walk":
            hp = out / "hardware.json"
            if hp.exists():
                h = json.loads(hp.read_text())
                h["walk"] = {"gpu_name": rec["gpu"], "rc": rc, "wall_s": rec["wall_s"]}
                hp.write_text(json.dumps(h, indent=1))
        else:
            hw.update(ended_utc=time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime()), rc=rc, job_wall_s=rec["wall_s"])
            (out / "hardware.json").write_text(json.dumps(hw, indent=1))
            if not j["keep_model"] and (out / "model.pt").exists():
                (out / "model.pt").unlink()
        with LOCK:
            ST["jobs"][name] = rec
        save()
        print(f"{time.strftime('%H:%M:%S')} lane {gi} end {name} rc {rc} wall {rec['wall_s']:.0f} s", flush=True)


th = [threading.Thread(target=run_lane, args=(i, lane)) for i, lane in enumerate(LANES)]
[t.start() for t in th]
[t.join() for t in th]
ST["end_s"] = time.time() - T0
ST["files"] = {str(p.relative_to(W)): p.stat().st_size for p in sorted(W.rglob("*")) if p.is_file()}
save()
print(json.dumps({k: v for k, v in ST.items() if k not in ("sha", "fp", "files")}, indent=1), flush=True)
